### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by thierryvolpiatto** [victorhge/iedit#108]
I see few answers in issues and no one in pull requests, so I wonder...

**Comment by victorhge** [comment]
Yes. And it is not actively maintained since I did not get more new ideas to improve it.

**Comment by thierryvolpiatto** [comment]
Victor Ren <notifications@github.com> writes:

> Yes. And it is not actively maintained since I did not get more new ideas to improve it.

Great! And thanks for this tool ;-)

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
