### ISSUE TITLE
iedit-number-occurrences is adding a space when incrementing

### ISSUE THREAD

**Issue by thierryvolpiatto** [victorhge/iedit#113]
A space is added after incremental number which is wrong:

![Capture d’écran_2020-08-20_12-07-14](https://user-images.githubusercontent.com/1533939/90757399-deb0cd00-e2dd-11ea-805b-6119eb0bdee3.png)

Give

![Capture d’écran_2020-08-20_12-07-44](https://user-images.githubusercontent.com/1533939/90757463-f5572400-e2dd-11ea-9be4-fe6781c465a2.png)

Which is wrong (notice the space after incremented numbers)
We want:

![Capture d’écran_2020-08-20_12-11-56](https://user-images.githubusercontent.com/1533939/90757818-6565aa00-e2de-11ea-8e75-6661a46875d8.png)

**Comment by thierryvolpiatto** [comment]
Seems the default value of `iedit-increment-format-string` have changed, which cause this behavior, setting it to `"%03d"` fix issue.

**Comment by duianto** [comment]
Confirmed. The space was added in this commit: https://github.com/victorhge/iedit/commit/735e374021598e25f6527b9dc7e2131f5dd55003

**Comment by victorhge** [comment]
Just change the default value of `iedit-increment-format-string'  to "%03d" in the latest commit def0c19ff77aef32ccf11eb118771a11cff59584

**Comment by thierryvolpiatto** [comment]
Victor Ren <notifications@github.com> writes:

> Just change the default value of `iedit-increment-format-string' to
> "%03d" in the latest commit def0c19

Thanks.

-- 
Thierry
