### ISSUE TITLE
iedit exits prematurely when inserting one of the electric pair characters (in emacs-27.1)

### ISSUE THREAD

**Issue by pkryger** [victorhge/iedit#114]
When:
- `electric-pair` is enabled,
- there is more than one occurrence,
- no region is active,

and one of the electric characters is typed (i.e., `(`) then `iedit-mode` exits updating only the occurrence where the point was. In addition, the following error appears in `*Messages*`:

```
Error in post-command-hook (iedit-update-occurrences-2): (wrong-type-argument number-or-marker-p nil)
```

I've created [a small gist](https://gist.github.com/pkryger/57bcfb77d66d78474a0a7c8ebee3744d) helping to reproduce the issue. One can copy it into an empty directory and then run it with

``` shell
$ emacs -Q -l iedit-electric-pair-reproduction.el
```

The gist does the following:
- installs `iedit`
- enables `electric-pair`
- inserts sample text with 2 occurrences (the issue is not happening when there's only one occurrence)
- enters `iedit-mode`
- inserts a `(` (to stimulate `electric-pair`)

I expect the text after the insertion to be:
```
()sample
()sample
```
and `iedit-mode` to be still enabled.

However, I'm getting:
```
()sample
sample
```
and `iedit-mode` is *not* enabled.

I tried to reproduce this with a couple of different `emacs`es. It doesn't happen on 26.3, but it is reproducible on 27.1 i.e., on  [Mitsuhary Yamamoto's `emacs-mac`](https://bitbucket.org/mituharu/emacs-mac/src/master/) and on [Docker silex/emacs](https://hub.docker.com/r/silex/emacs). To reproduce with the Docker 27.1 one I did (in a directory with the aforementioned gist):

``` shell
docker pull silex/emacs:27.1
docker run --rm -it -v $(pwd):$(pwd) silex/emacs:27.1 sh -c "cd $(pwd) && emacs -Q -l iedit-electric-pair-reproduction.el"
```

I'll try to debug this a bit, however, I'm not that familiar with the `iedit` internals and I'll appreciate any hints.

**Comment by victorhge** [comment]
Thanks for the report.  I just fixed in d9ebfb8
