### ISSUE TITLE
[feature request] make iedit skip invisible overlays

### ISSUE THREAD

**Issue by jixiuf** [victorhge/iedit#121]
I use https://github.com/vapniks/hide-lines to hide some lines, but when I call `iedit-mode` ,the invisible(hides) lines are selected and changed by Iedit, So Is it possible to ignore invisible lines .

**Comment by victorhge** [comment]
The feature is added in 0d5b1dd14aa1aef6dbd1dfdc2062d05a38b77c80.  Please check it out.
