### ISSUE TITLE
after-change-functions callback isn't invoked for all occurences in C modes

### ISSUE THREAD

**Issue by geza-herman** [victorhge/iedit#123]
`after-change-functions` callback isn't invoked for all occurences in C modes. This can cause problems for other packages which uses this callback. For example, lsp-mode doesn't get notified about all the changes. Maybe it would be a better solution to call all `after-change-functions`, except C mode ones.

I'm using this advice, and it seems that it handles the case better: editing is still responsive, and registered `after-change-functions` are still called (except C mode functions).

```lisp
  (advice-add 'iedit-update-occurrences-3 :around (lambda (orig-fun &rest args)
    (let ((before-change-functions (remove #'c-before-change before-change-functions))
          (after-change-functions (remove #'c-after-change after-change-functions)))
      (apply orig-fun args))
    (when (memq #'c-after-change after-change-functions)
      (apply 'c-after-change (cdr args))
    )
  ))
```

I know this advice is not perfect, `before-change-functions` are not called, but the current version doesn't call this either as far as I understand.

**Comment by victorhge** [comment]
This behavior was a workaround for slow c-before-change and c-after-change.   I retest it  on the latest Emacs.  It seems endurable without the workaround.   I will remove it.

**Comment by victorhge** [comment]
Done in 6eb7ff8191b1d271b6f4e7feb608dc72ca203a39
