### ISSUE TITLE
after iedit--quit is called, the value of line-move-ignore-invisible changed to nil 

### ISSUE THREAD

**Issue by jixiuf** [victorhge/iedit#124]
in `iedit-show-all`   `line-move-ignore-invisible` changed to nil, I think it should reset to original value after `iedit-show-all`.

Suppose  the value  of `line-move-ignore-invisible` is nil ,  When I use [`consult-focus-lines`  ](https://github.com/minad/consult)hide some lines in dired buffer,
`dired-previous-line` won't move the cursor to previous line.

So I think iedit should not change the value of  `line-move-ignore-invisible`

**Comment by victorhge** [comment]
Yes, you are right.  The usage was copied from outline mode.    `outline-minor-mode' should have the same problem.

**Comment by victorhge** [comment]
Fixed in https://github.com/victorhge/iedit/commit/5c792f5fd44797ece83169b7ef6ac6f4b259255d
