### ISSUE TITLE
Put `iedit-make-occurrences-overlays` in a variable to allow using something else

### ISSUE THREAD

**Issue by thierryvolpiatto** [victorhge/iedit#125]
Hello would it be possible to use something like:
```elisp
(defvar iedit-make-occurrences-overlays-function #'iedit-make-occurrences-overlays)
```
and `funcall` this variable where needed instead of calling directly `iedit-make-occurrences-overlays`.
I need this because I have to use a variant of `iedit-make-occurrences-overlays` that use something else than `re-search-forward` that accept a pattern with regexps separated with spaces:

```elisp
(defun iedit-make-occurrences-overlays (occurrence-regexp beg end)
  "Create occurrence overlays for `occurrence-regexp' in a region.
Return the number of occurrences."
  (setq iedit-aborting nil)
  (setq iedit-occurrences-overlays nil)
  (setq iedit-read-only-occurrences-overlays nil)
  ;; Find and record each occurrence's markers and add the overlay to the occurrences
  (let ((counter 0)
        (case-fold-search (not iedit-case-sensitive))
	(length 0)
        bounds)
    (save-excursion
      (save-selected-window
        (goto-char beg)
        (while (setq bounds (isl-multi-search-fwd occurrence-regexp end t))
          (let ((beginning (car bounds))
                (ending (cdr bounds)))
	    (if (and (> length 0) (/= (- ending beginning) length))
		(throw 'not-same-length 'not-same-length)
	      (setq length (- ending beginning)))
            (if (text-property-not-all beginning ending 'read-only nil)
                (push (iedit-make-read-only-occurrence-overlay beginning ending)
                      iedit-read-only-occurrences-overlays)
              (push (iedit-make-occurrence-overlay beginning ending)
                    iedit-occurrences-overlays))
            (setq counter (1+ counter))))))
    (iedit-update-index)
    counter))
```
Thanks.

**Comment by thierryvolpiatto** [comment]
See https://github.com/thierryvolpiatto/isearch-light/blob/0ea070419595255787f3de794a84986cf14dc633/isearch-light.el#L288
for more infos.

**Comment by victorhge** [comment]
AFAICS,  you don't want to redefine the whole  `iedit-make-occurrences-overlays'.  You just want to replace the call to `re-search-forward' with `isl-multi-search-fwd'.   Advising is more suitable for this situation, in my opinion.   Did you try it?

**Comment by thierryvolpiatto** [comment]
Victor Ren <notifications@github.com> writes:

> AFAICS, you don't want to redefine the whole
> iedit-make-occurrences-overlays'.

It is what I have to do anyway (more or less) with advice.

    (defun isl--advice-iedit-start (old--fn &rest args)
      (cl-letf (((symbol-function 'iedit-make-occurrences-overlays)
                 #'isl--iedit-make-occurrences-overlays))
        (apply old--fn args)))

> You just want to replace the call to re-search-forward' with
> `isl-multi-search-fwd'.

Not exactly, as the return value of isl-multi-search-fwd is not the same
as re-search-forward, it is a cons cell (beg . end).

> Advising is more suitable for this situation, in my opinion. Did you
> try it?

Yes, it is what I did finally, it works fine. So probably we can close
this, sorry for the noise.

Thanks.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry
