### ISSUE TITLE
[feature request] add flag to prevent iedit from putting the occurrence on the kill-ring in iedit-done()

### ISSUE THREAD

**Issue by ramblehead** [victorhge/iedit#128]
Would it be possible to make the following line optional to achieve Subj.:
https://github.com/victorhge/iedit/blob/0d6d2387188763a88cdf84f749e6f32d5a72bbd6/iedit.el#L573

I am not sure what is the use case for the kill-ring in iedit-done(). In my workflow this feature feels a bit annoying, which triggers my natural instinct to fork or def-advise. This time, I am trying to resist the instinct and post this issue to the otherwise brilliant iedit project!

It seems that evil-iedit-state is doing the same via hack:
https://github.com/syl20bnr/evil-iedit-state/blob/30fcfa96ceebed0191337c493f5c2efc8ae090ad/evil-iedit-state.el#L189

**Comment by victorhge** [comment]
94650d7
