### ISSUE TITLE
"iedit-goto-first-occurrence" is missing from iedit-lib.el

### ISSUE THREAD

**Issue by rcoacci** [victorhge/iedit#129]
It seems `iedit-goto-first-occurrence` got nuked from the lib at some point, causing the error `Wrong type argument: commandp, iedit-goto-first-occurrence` when invoked.

**Comment by rcoacci** [comment]
It seems that it got nuked on ff68c20, as 0d6d238 still have it.

**Comment by victorhge** [comment]
Yes.  Thanks for the reporting.  I will take it back.

**Comment by victorhge** [comment]
Fixed in 3247f30
