### ISSUE TITLE
When using `iedit-mode` directly (without slecting first), keyword do not get included in selection

### ISSUE THREAD

**Issue by florisie** [victorhge/iedit#130]
When using `iedit-mode` directly on `test` (without explicitly selecting it first) in a buffer containing e.g.:
```
test
:test
test:
```
then the latter two `test` patterns do not get included in the selections (sorry, I have only tested this on Spacemacs).
After explicitly selecting the word first, the command behaves correctly.

**Comment by victorhge** [comment]
iedit use symbol boundaries by default.   There is a variable 'iedit-use-symbol-boundaries' control it. You can set it to false.  Then word boundaries will be used, as you expected.
