### ISSUE TITLE
iedit and embark-mode

### ISSUE THREAD

**Issue by OrionRandD** [victorhge/iedit#132]
I have installed vertico and embark and 
embark just stole iedit default keybind
C-; 
and my Emacs every time is fired gives me this annoying Warning:

Warning (iedit): Iedit default key "C-;" is occupied by embark-act.

How can I fix this?

**Comment by victorhge** [comment]
M-x customize-variable Ret iedit-toggle-key-default
Change it other key or nil
Restart emacs.

**Comment by d1egoaz** [comment]
I also got hit by this warning.

I used:
```lisp
  (add-to-list 'warning-suppress-types '(iedit))
```

I wasn't expecting a minor mode to take on a `C-;` key binding, I thought I read minor modes should follow `C-c key` convention.
found it:
> Sequences consisting of C-c followed by any other ASCII punctuation or symbol character are allocated for minor modes. 

BTW thanks for this great package!
