### ISSUE TITLE
Is there a reason for commented-out requirement of cl-lib?

### ISSUE THREAD

**Issue by lelit** [victorhge/iedit#135]
I'm facing a problem apparently very similar to issue #117. 

After some investigation, it seems that it's due to incorrect byte compilation (I'm using Doom and thus straight, that automatically byte compiles included packages): effectively `iedit-lib.el` was patched in [that commit](https://github.com/victorhge/iedit/commit/f79846e6393813772ed89059452cea7911a9b425) to use `cl-case` instead of `case`.

Near the top of [that source](https://github.com/victorhge/iedit/blob/master/iedit-lib.el#L57) there is a commented out `(eval-when-compile (require 'cl-lib))`: if I uncomment that line (and recompile with `doom compile`), everything works as expected.

So, is there a specific reason why it was commented out (in commit 7a6a0d65)?

Thanks in advance and happy xmas!

**Comment by victorhge** [comment]
I guess I thought cl-lib was not used at that time. #
Strange enough, with or without that line, the compile result code is the same.
I have submit a commit to recall it back.

**Comment by lelit** [comment]
Thank you! Maybe the same should be applied to `iedit-rect.el`, as it uses `cl-rotatef` macro?

**Comment by lelit** [comment]
> Strange enough, with or without that line, the compile result code is the same.

I guess that depends whether you do the compilation with/without preloaded `cl-lib`, in other words if you do `emacs -Q -f byte-compile-file` you would hit the issue.
