### ISSUE TITLE
Symbol's value is void: iedit-is-narrowed

### ISSUE THREAD

**Issue by deuill** [victorhge/iedit#145]
Cleanups in 3fb4762 seem to have changed the names of some variables, including `iedit-is-narrowed` (which has had a `-local` suffix added to), but which have not been renamed consistently across `iedit.el`; there's references remaining for the old name, which cause errors to be thrown in a number of operations.

Thanks!

**Comment by jcs090218** [comment]
Getting the same error.

**Comment by Yevgnen** [comment]
Same issue here.

**Comment by victorhge** [comment]
Fixed https://github.com/victorhge/iedit/commit/44968bea9bff8fdd5bf9d227f53814c44bb9f619
