### ISSUE TITLE
:local attribute in iedit-lib.el is breaking emacs version > 26.3

### ISSUE THREAD

**Issue by sbroberg** [victorhge/iedit#146]
I recently did an elpa update recently (from Time-stamp: <2020-04-12 14:43:27 Victor Ren> to Time-stamp: <2022-01-14 12:33:25 Victor Ren>) and iedit now breaks on startup with the error:

error: Unknown keyword :local

for any version of emacs I'm using >= 26.3

The problem appears to be the :local in elpa-lib.el.  If I remove that line, everything works correctly.

I see that the .el files say "Compatibility: GNU Emacs: 22.x, 23.x, 24.x, 25.x".  Is iedit not supported for anything newer than 25.x?

**Comment by pstray** [comment]
Seems :local is a new thing, introduced with custom.el shipped with emacs 27.1.

**Comment by arvydasg** [comment]
Having the same issue here. Could you please tell me what did you do to make this package work?

I deleted the line :local t in file called "iedit-lib.el", but the problem persists. Same error "Unknown keyword :local" appears when I click `C-m ;`.

Looks like a cool plungin, hope I can use it one day. 

Thanks

**Comment by fixmaker** [comment]
> Having the same issue here. Could you please tell me what did you do to make this package work?
> 
> I deleted the line :local t in file called "iedit-lib.el", but the problem persists. Same error "Unknown keyword :local" appears when I click `C-m ;`.
> 
> Looks like a cool plungin, hope I can use it one day.
> 
> Thanks

@arvydasg I fixed this by deleting the line in `iedit-lib.el` and then byte compiling the file (while viewing the file, run `M-x emacs-lisp-byte-compile`).

**Comment by arvydasg** [comment]
> > Having the same issue here. Could you please tell me what did you do to make this package work?
> > I deleted the line :local t in file called "iedit-lib.el", but the problem persists. Same error "Unknown keyword :local" appears when I click `C-m ;`.
> > Looks like a cool plungin, hope I can use it one day.
> > Thanks
> 
> @arvydasg I fixed this by deleting the line in `iedit-lib.el` and then byte compiling the file (while viewing the file, run `M-x emacs-lisp-byte-compile`).

@fixmaker Thanks! Now it works great. Wohooo!

It was my first time editing emacs package source code... Thank for teaching me that simple C-x C-s is not enough for saving modifications made to such files.

**Comment by thierryvolpiatto** [comment]
Anyway,for any emacs versions, I guess `iedit-auto-buffering` should not be a local variable, it is just a flag to tell iedit to set (locally this time) `iedit-buffering`.

**Comment by victorhge** [comment]
:local removed in dd5d75b38ee0c52ad81245a8e5c932d3f5c4772d
