### ISSUE TITLE
In sh-mode or similar /$variable/ is not selected 

### ISSUE THREAD

**Issue by pierre-rouleau** [victorhge/iedit#148]
In sh-mode, bash-mode and similar modes,  when a variable name referred to using a single '$' character before the variable name and a slash after it that variable name is not selected.  

**Example:**

Inside the following iedit will select the two instances of `somefile` but only one instance of `someroot` and `somedir`

``` bash
someroot=abc
somedir=def
somefile=ghi
export DIRPATH=/$someroot/$somedir/$somefile
```

Is there a way to change the behaviour of iedit by chaning some user-option?

**Comment by victorhge** [comment]
The same issue was reported in issue  #134 .
Below is the comment I added in #134 :
I am afraid this cannot be fixed inside of Iedit. "/" is symbol in the syntax table of shell script mode.
There are several workarounds:

    Add (setq iedit-use-symbol-boundaries nil) to your sh-mode-hook
    Modify the syntax table by (modify-syntax-entry ?/ "." sh-mode-syntax-table).
    Mark 'section' first then enable iedit-mode

**Comment by pierre-rouleau** [comment]
@victorhge thanks for the suggestions (and for iedit)!
