### ISSUE TITLE
Allow `iedit-replace-occurrences` to use a sexp as replacement

### ISSUE THREAD

**Issue by thierryvolpiatto** [victorhge/iedit#150]
Hello,
would it make sense to use a sexp instead of a string for replacement in this function?
This would work just like in query-replace-regexp e.g. `\,(sexp)`.
One could use things like `format`, `format-time-string` etc...
The special placeholder `\&` would be provided.
I can provide a PR if interested.
Thanks.

**Comment by thierryvolpiatto** [comment]
#151 is providing this new feature.
It support also `\#` like `M-N` and add the possibility to do more things in Iedit, also completion on symbols and eldoc is provided in minibuffer, an history variable is also provide which allow not typing again your favorite sexps.

**Comment by thierryvolpiatto** [comment]
Here a small example:

![iedit](https://user-images.githubusercontent.com/1533939/192028831-4f0c40f2-f378-4386-af92-78914713b39a.gif)

**Comment by victorhge** [comment]
Thanks for the idea,  @thierryvolpiatto.

`query-replace-regexp` has this feature.   So I reused the code of module `replace` and commited a simple implementation -[6f69bd3](https://github.com/victorhge/iedit/commit/6f69bd3098d9865ed2e6acefb4aac4ae44cacc29).  please take a look.

**Comment by thierryvolpiatto** [comment]
Victor Ren ***@***.***> writes:

> Thanks for the idea, @thierryvolpiatto.
>
> query-replace-regexp has this feature. So I reused the code of module
> replace and commited a simple implementation -6f69bd3. please take a
> look.

Thanks for this. However I prefer my own implementation which is more
specific to iedit and provides completion and eldoc in minibuffer.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Victor Ren ***@***.***> writes:

> Thanks for the idea, @thierryvolpiatto.
>
> query-replace-regexp has this feature. So I reused the code of module replace and commited a simple implementation -6f69bd3. please take a look.

Also just tried your patch but it is not working, the whole sexp is
inserted i.e. it is not evaled.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ah! ok a pref arg is needed, ok with it it is working, however the counter seems indexed to 0, also as I said there is no completion and no eldoc.
Also the prefix arg is annoying (it is what I used in my first version, abandonned later) it is much better to detect the sexp if one.
