### ISSUE TITLE
Suggestion: include prefix-char ($@%*)  when searching in some modes (like perl)

### ISSUE THREAD

**Issue by pstray** [victorhge/iedit#40]
Would be nice to make iedit search for '$foo' when invoking it insted of just using 'foo', but making only the 'foo' part be editable.  Same goes for '@foo' and '%foo' and possibly '*foo'.

**Comment by victorhge** [comment]
With the latest iedit,  the scipt below might work  as you expect. The default occurrence will include the prefix char.
(add-hook 'perl-mode-hook
          '(lambda ()
             (setq iedit-current-symbol
                   '(lambda ()
                      (let* ((bound (bounds-of-thing-at-point 'symbol))
                             (prefix-char (char-after (1- (car bound)))))
                        (if (memq prefix-char '(?$ ?% ?@ ?*))
                            (progn 
                              (setq iedit-only-complete-symbol-local nil)
                              (buffer-substring-no-properties (1- (car bound)) (cdr bound)))
                          (buffer-substring-no-properties (car bound) (cdr bound))))))))

**Comment by pstray** [comment]
Cant find any reference to iedit-current-symbol in the iedit i upgraded to
a few days ago...

Before that it did add the prefix to the string, but didnt match anything
because of the \_< before it in the regexp

On Sun, Jun 12, 2016 at 7:54 AM, victorhge <notifications@github.com> wrote:

> With the latest iedit, the scipt below might work as you expect. The
> default occurrence will include the prefix char.
> (add-hook 'perl-mode-hook
> '(lambda ()
> (setq iedit-current-symbol
> '(lambda ()
> (let* ((bound (bounds-of-thing-at-point 'symbol))
> (prefix-char (char-after (1- (car bound)))))
> (if (memq prefix-char '(?$ ?% ?@ ?*))
> (progn
> (setq iedit-only-complete-symbol-local nil)
> (buffer-substring-no-properties (1- (car bound)) (cdr bound)))
> (buffer-substring-no-properties (car bound) (cdr bound))))))))
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/victorhge/iedit/issues/40#issuecomment-225411701>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAWGjzikL8mjXDEoGpgagLBrxx8kMK4Uks5qK58igaJpZM4AwWLB>
> .
>



-- 
  Peder Stray
