### ISSUE TITLE
Make it possible to toggle value of iedit-only-at-symbol-boundaries

### ISSUE THREAD

**Issue by rpglover64** [victorhge/iedit#43]
I recently found myself needing to change all occurrences of "pdf-view" to "pdf-tools" in a buffer. A perfect job for IEdit, I thought. I was a little surprised that when "pdf-view" occurred as part of a variable name rather than the whole symbol, IEdit ignored it.

This is good default behavior, but sometimes I want the other one; it would be useful to have something analogous to `iedit-toggle-case-sensitive`.

**Comment by lewang** [comment]
Did you try selecting the string you want?

On Fri, Mar 27, 2015 at 12:25 PM, Alex R <notifications@github.com> wrote:

> I recently found myself needing to change all occurrences of "pdf-view" to
> "pdf-tools" in a buffer. A perfect job for IEdit, I thought. I was a little
> surprised that when "pdf-view" occurred as part of a variable name rather
> than the whole symbol, IEdit ignored it.
>
> This is good default behavior, but sometimes I want the other one; it
> would be useful to have something analogous to iedit-toggle-case-sensitive
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victorhge/iedit/issues/43>.
>



-- 
Le

**Comment by rpglover64** [comment]
I had not.

That works. I missed the relevant portion of the `iedit-mode` documentation, namely:

> If region is not active, the current symbol (returns from `iedit-current-symbol`) is used as the occurrence by default. The occurrences of the current symbol, but not include occurrences that are part of other symbols, are highlighted.  If you still want to match all the occurrences, even though they are parts of other symbols, you may have to mark the symbol first.

My apologies.
