### ISSUE TITLE
tab doesn't work in gui Emacs

### ISSUE THREAD

**Issue by michael-heerdegen** [victorhge/iedit#44]
Hello,

in the gui version of Emacs, hitting the tab key after entering "iedit-mode" doesn't call "iedit-next-occurrence" but the global binding of tab.  Works in terminal however.  This helps:

```
(define-key iedit-lib-keymap [tab] 'iedit-next-occurrence)
```

Can we please fix this in the source?  Thanks.

**Comment by victorhge** [comment]
It is in now.  Thanks.

**Comment by michael-heerdegen** [comment]
victorhge <notifications@github.com> writes:

> It is in now. Thanks.

Thanks!
