### ISSUE TITLE
Add to MELPA stable?

### ISSUE THREAD

**Issue by mkleehammer** [victorhge/iedit#45]
Could you also add to MELPA stable, please?  Because it only includes commits marked with release tags, I would expect it to become one of the more popular repositories over time.

**Comment by mkleehammer** [comment]
It looks like a recipe is in place for MELPA to build from your GitHub repository.  However, they won't go into stable unless there are tags with actual release versions like "1.2.3" or "v1.2.3".  Can you add some tags for releases?  Thanks.

**Comment by victorhge** [comment]
I added a release
