### ISSUE TITLE
Feature: sublime style incremental select

### ISSUE THREAD

**Issue by axyz** [victorhge/iedit#46]
It would be nice to have something like sublime's `CTRL-d` that incrementally selects next occurrences.

I know that is possible to expand the region below or on top, but as I've seen there's no way to select only the next occurrence and not just the next line (that could or could not have one or more than one occurrences)

**Comment by Wilfred** [comment]
For what it's worth, if you have highlight-symbol installed, you can go the first instance, activate the region, then call `highlight-symbol-next` to expand the region by occurrences.

**Comment by victorhge** [comment]
Just submit a commit 52c4865.  sublime style work flow should works,  Just a little bit more key stokes.

Please let me know how you feel about it.
