### ISSUE TITLE
Wrong behavior when deleting text from inside an occurrence to end of line 

### ISSUE THREAD

**Issue by bmag** [victorhge/iedit#53]
With Emacs 24.5 and latest version of iedit, I experience weird behavior when the cursor is inside an occurrence and I delete the text from the cursor to the end of the line.

To reproduce:
- 1. `emacs -Q -L /path/to/iedit/directory`
- 2. `M-: (require 'iedit)`
- 3. change contents of scratch buffer to this:
```
foobar qux
foobar qux
```
- 4. move cursor to "b" in the first line
- 5. `M-x iedit-mode` -> "foobar" in both lines is highlighted
- 6. `C-k` (`kill-line`)  

Expected result: buffer will look like this, with "foo" highlighted in both lines:
```
foo qux
foo qux
```
Actual result: iedit-mode is deactivated (nothing is highlighted), buffer looks like this:
```
foo
foobar qux
```

Original Issue reported by @jdwaterson here: https://github.com/syl20bnr/spacemacs/issues/3193

**Comment by PierreR** [comment]
The same issue happens with `c-w` instead of `c-k`.

**Comment by victorhge** [comment]
The behavior is expected.

iedit-lib.el: 348
348:  replacement.  If this modification is going out of the
349:  occurrence, it will abort Iedit mode."
