### ISSUE TITLE
Misbehaving command 'iedit-mode after custom mapping.

### ISSUE THREAD

**Issue by bibek22** [victorhge/iedit#55]
I mapped iedit-mode to "C-i" globally. 
`(define-key global-map (kbd "C-i") 'iedit-mode)`

Now when I press that key "C-i", it gets me to iedit-mode alright. But when I press the combination again it doens't turn off iedit-mode. It basically functions as iedit-next-occurance ? Am I missing something?

**Comment by victorhge** [comment]
"C-i" is TAB in Emacs.   TAB is one of key binding in iedit-lib-keymap for iedit-next-occurance.   Just key binding confliction.    Either you solve the confiction or choose another key without confiction.
