### ISSUE TITLE
Suggestion: select all the occurrences after point.

### ISSUE THREAD

**Issue by Wilfred** [victorhge/iedit#56]
Sometimes I want to replace all the occurrences after point, rather than all the occurrences in a function or buffer.

Since C-u 0 means 'within the function', perhaps C-u 1 could be used?

**Comment by glucas** [comment]
The prefix `1` is also already used: it means to start with just one match. You would use this if you want to manually extend the matches using e.g. M-n / M-p.

**Comment by Wilfred** [comment]
Thanks, I didn't know you could do that!

How about a negative prefix argument then? As far as I can see -1 is unused.

**Comment by victorhge** [comment]
There is a more general feature  I forgot to  mention:

If Iedit mode is on and region is active, Iedit mode is
restricted in the region, e.g. the occurrences outside of the
region is excluded.
If Iedit mode is on and region is active, with an universal
prefix argument, Iedit mode is restricted outside of the region,
e.g. the occurrences in the region is excluded.

If you want a shortcut to this,  I think a keyboard macro is sufficient.
