### ISSUE TITLE
Only one passing test on emacs-25

### ISSUE THREAD

**Issue by dunn** [victorhge/iedit#57]
Running `iedit-tests.el` with the current development branch ends up with 26 failing tests: https://gist.github.com/dunn/d2370dc951a2a2df3bdc

Is this an issue with Emacs 25, iedit, or my ert setup?

**Comment by mgalgs** [comment]
iedit has been broken on emacs-25 for me as well.  The worst part is that it works fine with `emacs -Q`, so it's interacting with something else...

I bisected emacs and found that the commit breaking things is:

```
commit 564d811725596f15ecf543777e11504b47d2af86
Author: Eli Zaretskii <eliz@gnu.org>
Date:   Fri Nov 6 17:19:39 2015 +0200

    Don't invoke overlay modification hooks in wrong buffer
    
    * src/buffer.c (report_overlay_modification): When called with
    AFTER non-zero, don't invoke overlay modification hooks if the
    buffer recorded in last_overlay_modification_hooks is different
    from the current buffer.  (Bug#21824)
```

I've been running with that guy reverted for a month or so and it's been working well.  [I reported this upstream](https://lists.gnu.org/archive/html/emacs-devel/2015-12/msg00425.html) but didn't have an `emacs -Q` recipe so it never really went anywhere.

BTW, I'm on Linux so I don't think this issue should be tagged with [OSX 10.11.2].

**Comment by dunn** [comment]
Thanks!

**Comment by victorhge** [comment]
Now all test cases pass.

**Comment by dunn** [comment]
Thanks! If things are in a stable state, it'd be great to have another tagged release for MELPA stable.
