### ISSUE TITLE
Difference with multiple-cursors?

### ISSUE THREAD

**Issue by Silex** [victorhge/iedit#58]
Hello,

What is the difference with https://github.com/magnars/multiple-cursors.el ?

**Comment by lewang** [comment]
I used iedit for a long time, and really enjoyed it.

Multiple cursors allow you to navigate out of the selected-region, in my use-cases that makes MC more flexible.  However some are more used to the iedit workflow.

A lot of the niftier iedit features such as hiding unmatched lines are now availbele in MC.

**Comment by Silex** [comment]
Ah, interesting. Does `iedit` predate `multiple-cursors`?

**Comment by victorhge** [comment]
I tried `mulitple-cursors` today.  Pretty cool.  It seems more like a clone feature of "multiple selection" in Sublime Text. 

 MC's  workflow starts from  occurrences and  can modify the text around the occurrences. But you can not navigate out of the line.  I think `iedit` might be able to borrow something from it.

**Comment by Silex** [comment]
Given I had my answer I'm closing this.
