### ISSUE TITLE
C-; binding overrides user binding

### ISSUE THREAD

**Issue by Malabarba** [victorhge/iedit#59]
First of all, let me say thanks to everyone who contributes to iedit.

I ran into this problem after installing another package that depends on iedit. I have a keybind under `C-;`, and after an upgrade today I was perplexed to find it had been overriden by a mode which I've never used before.

[The keybinding convention](http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) recommends "C-c followed by any other punctuation character" for minor modes. But mostly, it was just confusing to find such a low-level key overriden.

Could you check whether the key is not already taken before binding it?

Best,

**Comment by victorhge** [comment]
Good suggestion.  Done.
https://github.com/victorhge/iedit/commit/d335d6842a61dbbe55dd938e73d999bc919faa92

**Comment by Malabarba** [comment]
Thanks!

**Comment by danrharms** [comment]
This code change is now warning me that iedit mode is overriding my custom key-binding for... iedit mode. :)

Is there a way to check that the key-binding is truly different before issuing the warning?

You may be wondering why I do that. I use use-package, and its :bind command to defer loading of iedit until I issue the command. I would like to defer loading of iedit, but I like the default binding of C-;

Let me know what you think. 

Thanks

**Comment by victorhge** [comment]
You have find a way :).   Thanks for the patch.
