### ISSUE TITLE
iedit-expand-up/down-to-occurrence seem flipped

### ISSUE THREAD

**Issue by danrharms** [victorhge/iedit#61]
THe current binding is counter-intuitive to me.  It seems that "\M-p", which everywhere else in emacs is bound to an action that goes backward, is here used to expand the region forward, and "\M-n" used elsewhere for actions that go ahead, is here used to expand the region backward.  Could these be flipped?  If you like I can make a pull request.

Nice feature, by the way.

**Comment by danrharms** [comment]
It appears I was looking at an outdated commit.  Sorry.

**Comment by victorhge** [comment]
I will replace them with C-< / C->. 
The original key binding is M-[, which is a prefix when emacs is running in term.  It is really hard to find a proper key binding for them.  Any suggestion?
