### ISSUE TITLE
[Feature request] iedit-mode support html paired tags real-time rename.

### ISSUE THREAD

**Issue by zw963** [victorhge/iedit#62]
Iedit-mode is very cool. I very love the way of this package work,
especial real-time visibility changing, very cool.

if we could extend this package to support following, more usable.
```html
<foo>
  ....
</foo>
```
rename foo to bar
```html
<bar>
 ...
</bar>
 ```

**Comment by victorhge** [comment]
I found a sgml-electric-tag-pair-mode when I investigated how to implement this feature.   It works already as you expect, in my opinion.    The mechanism is the same as iedit, just the pair is not highlighted.   Let me know if it is what you wanted.

**Comment by zw963** [comment]
Yes, this is what i want. though, it not as pefect as iedit behavior.
Thanks you very much for help.
