### ISSUE TITLE
'C-;' is not working

### ISSUE THREAD

**Issue by aodock** [victorhge/iedit#67]
hi, im using `evil` and the default key is not working. But when i do `M-x iedit-mode` i get a text below the status bar saying " _you can activate iedit-mode by `C-;`_"

**Comment by victorhge** [comment]
What you saw is normal if  you install Iedit from ELPA.   The default key binding is enabled when iedit module is loaded into Emacs.   To enable it always, you have to add the following to your .emacs file:
`(require  'iedit)`
