### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by chrissound** [victorhge/iedit#68]
Hi there, emacs noob reporting in.

How do I go about installing this?

**Comment by duianto** [comment]
Iedit is available in the MELPA repository. To be able to install packages from MELPA, do the following:

#### Create a .emacs file in your home directory
Linux / Mac
`~/.emacs`

Windows:
`%userprofile%\appdata\roaming\.emacs`
the full path without the `%userprofile%` variable is:
`c:\users\(username)\appdata\roaming\.emacs`
replace (username) with the username of the logged in user.

##### Windows File Explorer issue
There's an issue with the windows file explorer, when a file is renamed to start with a . (period), then windows shows this error message: 

> Rename
> You must type a file name.

##### Solution
A workaround that solves this is to add a period to the end of the filename, like this: `.emacs.`. The ending period gets deleted automatically, leaving only `.emacs`.

#### Modify the .emacs file
Add the following lines:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)
```

#### Install iedit
- Start Emacs
- Press: <kbd>M-x</kbd>
- Type: `package-install`, a "Install package: " prompt appears at the bottom (in the minibuffer)
- Type: `iedit`
- Press: <kbd>Return</kbd>

#### Enable Iedit
Iedit has to be enabled before the <kbd>C-;</kbd> keybinding can be used to toggle iedit on/off.
- Press <kbd>M-x</kbd>
- Type: `iedit-mode`
- Press: <kbd>Return</kbd>

It will select every occurrence of the word/symbol under the cursor.

#### Enable iedit on startup
To enable iedit-mode automatically when emacs starts, add the following command to the .emacs file:
`(require 'iedit)`


#### Keybindings
The keybindings can be viewed in a help window by first entering iedit mode, and then pressing <kbd>C-h b</kbd>.
```
Iedit Mode Bindings: key             binding
---             -------

C-h		Prefix Command
TAB		iedit-next-occurrence
ESC		Prefix Command
C-'		iedit-toggle-unmatched-lines-visible
<S-iso-lefttab>			iedit-prev-occurrence
<S-tab>		iedit-prev-occurrence
<backtab>	iedit-prev-occurrence
<f1>		Prefix Command
<help>		Prefix Command
<tab>		iedit-next-occurrence

M-;		iedit-toggle-selection

<f1> C-h	iedit-help-for-help
<f1> ?		iedit-help-for-help
<f1> b		iedit-describe-bindings
<f1> k		iedit-describe-key
<f1> m		iedit-describe-mode
<f1> q		help-quit
<f1> <f1>	iedit-help-for-help
<f1> <help>	iedit-help-for-help

<help> C-h	iedit-help-for-help
<help> ?	iedit-help-for-help
<help> b	iedit-describe-bindings
<help> k	iedit-describe-key
<help> m	iedit-describe-mode
<help> q	help-quit
<help> <f1>	iedit-help-for-help
<help> <help>	iedit-help-for-help

C-h C-h		iedit-help-for-help
C-h ?		iedit-help-for-help
C-h b		iedit-describe-bindings
C-h k		iedit-describe-key
C-h m		iedit-describe-mode
C-h q		help-quit
C-h <f1>	iedit-help-for-help
C-h <help>	iedit-help-for-help

key             binding
---             -------

ESC		Prefix Command
C-?		iedit-help-for-occurrences
<remap>		Prefix Command

M-C		iedit-toggle-case-sensitive
M-G		iedit-apply-global-modification
M-H		iedit-restrict-function
M-I		iedit-restrict-current-line
M-n		iedit-expand-down-to-occurrence
M-p		iedit-expand-up-to-occurrence
M-{		iedit-expand-up-a-line
M-}		iedit-expand-down-a-line

<remap> <keyboard-escape-quit>	iedit-quit
<remap> <keyboard-quit>		iedit-quit

M-SPC		iedit-blank-occurrences
M-<		iedit-goto-first-occurrence
M->		iedit-goto-last-occurrence
M-B		iedit-toggle-buffering
M-D		iedit-delete-occurrences
M-L		iedit-downcase-occurrences
M-N		iedit-number-occurrences
M-R		iedit-replace-occurrences
M-U		iedit-upcase-occurrences
```

**Comment by victorhge** [comment]
Thanks, duianto.  You are increadible.  　I was planning to include some install instruction in readme file....
