### ISSUE TITLE
The default keybinding doesn't work

### ISSUE THREAD

**Issue by MalcolmChen** [victorhge/iedit#70]
I've try `(global-set-key [(control ?\;)] 'iedit-mode)` and `(require 'iedit)`;
and neither of them make the keybinding `C-;` work correctly.
And i am using Emacs in X-windows.
The keybinding `C-;` only show something looks like pop-tip, and the "pop-tip" got all the content of clipboard on it - shows by a list that have a number before every item , i can press the number to choose one item and it will be paste to Emacs's buffer ... 
I've try remove all the  package , and `C-;` shows the "pop-tip" too , i don't know to make `C-;` work for iedit

**Comment by victorhge** [comment]
It seems C-; is bound to something else.   Please check it by pressing "C-h k C-;" .
You may have to choose a new key for either iedit or the current binding.

**Comment by nickmccurdy** [comment]
I noticed that `flyspell-auto-correct-previous-word` was bound to `C-;`. It may help to change `iedit`'s deafult bind (or add an alternate default time) since `flyspell` is part of Emacs and people may be used to that bind.

**Comment by MalcolmChen** [comment]
Sorry for not reply immediately. C-h k can't describer the `C-;`, no matter when i press `C-;`,Emacs just give me the damn pop-up. Even i delete my init.el , any tips?

**Comment by nickmccurdy** [comment]
What happens when you run `C-h k C-;`? Does it run the command directly?

**Comment by MalcolmChen** [comment]
@nickmccurdy yep, it just show the pop-tip directly, `C-;` can't be sent to key-describer. and i've try to find out if `C-;` is gnome's keybinding and got nothing. BTW, i'm using debian 8.

**Comment by nickmccurdy** [comment]
Hm, I wonder if you could figure out if Emacs is receiving that bind from the minibuffer or messages buffer.

**Comment by MalcolmChen** [comment]
@nickmccurdy  sry, i don't know how ... but Emacs does that on both my computer and one of them got fresh system. Doesn't your Emacs behavior like mine ?

**Comment by danrharms** [comment]
Just in case:  are you running emacs in a GUI or terminal?  The "C-;" key-binding may not be transferred correctly to emacs by the terminal emulator.

**Comment by nickmccurdy** [comment]
@MalcolmChen `C-;` works in [my `.emacs.d`](https://github.com/nickmccurdy/dotfiles/tree/master/home/.emacs.d), but it isn't bound if I run Emacs with `--quick` (which disables init files). I think @danrharms found the problem though, since `C-h k C-;` doesn't even run if I launch Emacs from a terminal (implying that Emacs isn't even receiving the keypress).

**Comment by MalcolmChen** [comment]
@danrharms i run emacs in GUI. this issue gonna takes lots time cause the jet lag :) i'll try in terminal and fedback ... just waiting

**Comment by nickmccurdy** [comment]
That's odd, what OS/DE are you running? It might be binding `C-;`.

**Comment by MalcolmChen** [comment]
@nickmccurdy I'm using Debian 8. and i've find out it's not the issue of emacs. `C-;` maybe keybinding of gnome. cuz it does the same thing in gnome-terminal and gedit, even chrome. and i've find no way to disable it. that sucks. i'm gonna to find some help in stackoverflow. thank you, guys. i'm gonna close this issue.
