### ISSUE TITLE
Leaves buffer with no current mark

### ISSUE THREAD

**Issue by mkrauss** [victorhge/iedit#71]
For some reason if I set the mark, invoke iedit-mode, then end
iedit-mode, the buffer no longer has a mark set. This means that using
popping the mark or exchanging it with point, as I often do for quick
navigational purposes, does not work. Most Emacs commands will leave
the last mark in place or set a new one pushing back on the mark ring.

Iedit is so *excellent* I continue to use it regularly in spite of
this annoyance. Thanks for it!

**Comment by victorhge** [comment]
iedit-mode does not manipulate the mark-ring at all.  For me, the mark-ring is still there.  One way I can think of to trouble-shoot is to set `edebug-global-break-condition' to (null mark-ring).   Please come back with the back trace.

**Comment by victorhge** [comment]
I can not see the problem.
Please come back with the back trace requested

**Comment by mkrauss** [comment]
I do not seem to have this problem anymore. No idea what changed. I'll come back with the back trace if it starts happening again. So weird.

Thank you for looking in to it!
