### ISSUE TITLE
Naming: `iedit-toggle-unmatched-lines-visible`

### ISSUE THREAD

**Issue by xged** [victorhge/iedit#74]
It would be more clear if `iedit-toggle-unmatched-lines-visible` would be just called `iedit-toggle-fold` (`iedit-toggle-fold-unmatched-lines`).

**Comment by victorhge** [comment]
For me, ` iedit-toggle-fold` and `iedit-toggle-fold-unmatched-lines` are not improving clarity.  They are about on the same level.  `fold` is a metaphor and more indirectly.   Different people may have different opinion.   If we want to change it, we need a better name.

This function is to hide or show the lines between the highlights.   In iedit-mode it is called ‘unmatched lines".   How about "iedit-showhide-unmatched-line"?

**Comment by victorhge** [comment]
I will go for `iedit-show/hide-unmatched-lines` anyway.
