### ISSUE TITLE
buggy behaviour in some buffers

### ISSUE THREAD

**Issue by kermorgant** [victorhge/iedit#75]
Hello,

Thanks for this package. Just discovered it and am so sad about an issue preventing its use in my php buffers.

After selecting the string to be replaced, only part of it gets replaced as shown in video here : https://videobin.org/+isn/mw7.html

Not sure about what details I could give you. Please let me know how I could help you debugging this more if you can have a look at that. 
 (my configuration is here if that might give some contextual info : https://github.com/kermorgant/.emacs.d)

**Comment by victorhge** [comment]
I tried your configuration.  But I was not able to reproduce your problem.  
One different is I did not load your local.org file.
Do you always have this problem in php buffer?

**Comment by kermorgant** [comment]
Thanks for trying. Yes, it still occurs so I will try to find some time to isolate the problem in the coming days.

**Comment by kermorgant** [comment]
Hello. I finally took a moment to look at it and it begun working after disabling ggtags-mode in my configuration.

**Comment by victorhge** [comment]
Glad to hear the news.


BR/
Victor Ren

On Wed, Aug 30, 2017 at 6:36 PM, Mikael Kermorgant <notifications@github.com
