### ISSUE TITLE
Replace from specific line to the end down (> 10 matches)

### ISSUE THREAD

**Issue by lmdic** [victorhge/iedit#78]
Windows 10, Emacs 25.1, package iedit

Suppose I has text:

1.aaa_1111_hello
2.aaa_2222_hello
3.aaa_1111_hello
4.aaa_4444_hello
5.aaa_1111_hello
6.aaa_5555_hello
7.aaa_1111_hello
8.aaa_1111_hello
...
100.aaa_1111_hello

I want to replace all (100 lines) "_1111" by text "_zero"

Steps:

Select text "_1111"
1.`M-x iedit-mode`
2.`M-D` (to delete all find text **_1111**)
3.Input new text **_zero**

Here result.

1.aaa_zero_hello
2.aaa_2222_hello
3.aaa_zero_hello
4.aaa_4444_hello
5.aaa_zero_hello
6.aaa_5555_hello
7.aaa_zero_hello
8.aaa_zero_hello
...
100.aaa_zero_hello

OK.

But now I want to replace text ONLY from line "5.aaa_1111_hello" and to the end down. 
So as result I need to replace 98 lines. 

The result must like this:

1.aaa_1111_hello
2.aaa_2222_hello
3.aaa_1111_hello
4.aaa_4444_hello
5.aaa_zero_hello
6.aaa_5555_hello
7.aaa**_zero**_hello
8.aaa**_zero**_hello
...
100.aaa**_zero**_hello

Is it possible by iedit?

**Comment by victorhge** [comment]
Yes. Start from step 2,   active a region  from the line to the end. 
Then M-x iedit-mode again.  

If Iedit mode is on and region is active, Iedit mode is
restricted in the region, e.g. the occurrences outside of the
region is excluded.
If Iedit mode is on and region is active, with an universal
prefix argument, Iedit mode is restricted outside of the region,
e.g. the occurrences in the region is excluded.

When only the occurrences you want to replaced are highlighted, you can start your editing.

**Comment by lmdic** [comment]
Cool. Thank you!!!!
