### ISSUE TITLE
Failure of finding matches

### ISSUE THREAD

**Issue by qqlearn123** [victorhge/iedit#81]
EXAMPLE: I have the following text in the buffer - 
**This is**

When I put the cursor between i and s and then press <C-;>, there is an error called "0 matches for http://is".

Anybody knows what is the cause for this? (My emacs version is 23.1.1)

Thanks!

**Comment by victorhge** [comment]
Would you  provide a recipe starting from "emacs -Q" to
reproduce the problem?

**Comment by articuluxe** [comment]
Execute ‘toggle-debug-on-error, reproduce, then post the stacktrace.
