### ISSUE TITLE
lag when editing with iedit-mode on

### ISSUE THREAD

**Issue by netjune** [victorhge/iedit#83]
When editing c++ file (less than 3000 lines) with iedit-mode on, and there are no more than 10 matches, it lags too much. Emacs uses more than 80% of cpu when typing chars.

Not 100% reproduciable. But it happens too often.

**Comment by articuluxe** [comment]
You might want to specify your os and emacs versions. Also how many other packages you’ve installed; can you try disabling some and trying to reproduce?

Otherwise running the emacs profiler while reproducing might give some clues.

**Comment by victorhge** [comment]
I checked `c-after-change'.  'c-before-font-lock-functions'  are called in mapc.   I guess it's the bottleneck. 
In my setup, the value of 'c-before-font-lock-functions' is "(c-neutralize-syntax-in-and-mark-CPP c-change-set-fl-decl-start)" .   Please post yours.

**Comment by netjune** [comment]
Mine is:

`(c-depropertize-new-text c-parse-quotes-after-change c-extend-font-lock-region-for-macros c-after-change-re-mark-raw-strings c-neutralize-syntax-in-CPP c-restore-<>-properties c-change-expand-fl-region)`

How about combining the calls of functions in after-change-functions? Only call them when iedit done?

**Comment by amosbird** [comment]
Try this
```lisp
(defun +amos*yes () t)
(add-hook! 'iedit-mode-hook
  (when (memq major-mode '(c-mode c++-mode))
              (advice-add #'lsp-on-change :override #'ignore)
              (advice-add #'c-font-lock-fontify-region :override #'ignore)
              (advice-add #'c-called-from-text-property-change-p :override #'+amos*yes)))

(add-hook! 'iedit-mode-end-hook
  (when (memq major-mode '(c-mode c++-mode))
              (advice-remove #'lsp-on-change #'ignore)
              (lsp-on-revert)
              (advice-remove #'c-font-lock-fontify-region #'ignore)
              (save-excursion
                (font-lock-fontify-region 0 (buffer-size) nil))
              (advice-remove #'c-called-from-text-property-change-p #'+amos*yes)))
```

**Comment by netjune** [comment]
Good idea.

There is a macro `combine-after-change-calls` in emacs. It is like this:
```
(defmacro combine-after-change-calls (&rest body)
  "Execute BODY, but don't call the after-change functions till the end.
If BODY makes changes in the buffer, they are recorded
and the functions on `after-change-functions' are called several times
when BODY is finished.
The return value is the value of the last form in BODY.

If `before-change-functions' is non-nil, then calls to the after-change
functions can't be deferred, so in that case this macro has no effect.

Do not alter `after-change-functions' or `before-change-functions'
in BODY."
  (declare (indent 0) (debug t))
  `(unwind-protect
       (let ((combine-after-change-calls t))
	 . ,body)
     (combine-after-change-execute)))
```

What about the following idea:
1. set `combine-after-change-calls` to t in `iedit-mode-hook`
2. call `combine-after-change-execute` and then set `combine-after-change-calls` back to nil

**Comment by victorhge** [comment]
> Good idea.
> 
> There is a macro `combine-after-change-calls` in emacs. It is like this:
> 
> ```
> (defmacro combine-after-change-calls (&rest body)
>   "Execute BODY, but don't call the after-change functions till the end.
> If BODY makes changes in the buffer, they are recorded
> and the functions on `after-change-functions' are called several times
> when BODY is finished.
> The return value is the value of the last form in BODY.
> 
> If `before-change-functions' is non-nil, then calls to the after-change
> functions can't be deferred, so in that case this macro has no effect.
> 
> Do not alter `after-change-functions' or `before-change-functions'
> in BODY."
>   (declare (indent 0) (debug t))
>   `(unwind-protect
>        (let ((combine-after-change-calls t))
> 	 . ,body)
>      (combine-after-change-execute)))
> ```
> 
> I see `c-after-change` is called in after-change-functions.
> 
> What about the following idea:
> 
>     1. set `combine-after-change-calls` to t in `iedit-mode-hook`
iedit already has a similar thing for this.  You can add `(iedit-start-buffering)` to `iedit-mode-hook`

> 
>     2. call `combine-after-change-execute` and then set `combine-after-change-calls` back to nil in `iedit-mode-end-hook`

**Comment by victorhge** [comment]
@netjune just commit a new option `iedit-auto-bufferring` .  It could be set in your c-mode-hook.

**Comment by netjune** [comment]
Thanks. I will try it later.

**Comment by netjune** [comment]
I reported a bug to emacs. The author of the cc-mode replied. There is a question about the use of after-change-functions in iedit. Do you have time to have a look at it?

The emacs bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=35316
