### ISSUE TITLE
iedit-mode seems to be broken in Emacs 26.1

### ISSUE THREAD

**Issue by vvv** [victorhge/iedit#84]
`M-x iedit-mode` does highlight matches, and I am able to navigate between them.  But when I edit any of the matches, only the match I've edited is changed, the rest are not.

`iedit-mode` started to misbehave after I upgraded to Emacs 26.1.

Could somebody please confirm/refute this regression report?

**Comment by articuluxe** [comment]
iedit-mode works for me on emacs 26.1 running on High Sierra. You may need to evaluate what other packages you are running that could interfere.

**Comment by gyst** [comment]
I have the same problem on 25.2.2 if I also have `diff-hl-mode` enabled *and* diff changes highlighted. Disabling `diff-hl-mode` makes iedit work as expected again. Annoying, I'd like to use both modes at the same time.

**Comment by gyst** [comment]
Update: this workaround is nice for me, perhaps useful for somebody else. In my `.emacs`:
```
(add-hook 'iedit-mode-hook (lambda () (diff-hl-mode -1)))
(add-hook 'iedit-mode-end-hook (lambda () (diff-hl-mode +1)))
```

**Comment by vvv** [comment]
I've restarted my computer (security update). `iedit-mode` works now.  It must have been some temporary glitch of my Emacs...

Sorry for the noise.

**Comment by glucas** [comment]
I don't use diff-fil-mode, and I've seen this behavior intermittently for a while (on Emacs 25 and 26). I haven't yet narrowed down the conditions under which it happens -- usually when I hit this problem  some combination of retrying and navigating around "fixes" it, without changing any other modes/settings.
