### ISSUE TITLE
iedit-restrict-function doesn't update mode-line text correctly

### ISSUE THREAD

**Issue by duianto** [victorhge/iedit#85]
#### Description
The `Iedit: 1/3` mode-line text, doesn't update correctly after calling `iedit-restrict-function`.

#### Steps to reproduce
- Start Emacs
- Open a new buffer `C-x b` `test`
- Copy and paste this example text:
```
;; pre function comment

(defun test ()
;; first comment
;; second comment
;; third comment
)

;; post function comment
```
- place the cursor on the word "comment", on the line:
```
;; second comment
```
- Enter Iedit state: `C-;`, the mode-line correctly shows: `Iedit:3/5`
- Restrict the occurrences to the current function: `S-M-h`

#### Observed behaviour:
The modeline now shows `Iedit:0/3`
The total number of occurrences `3` has updated correctly, but the current occurrence shows `0`.

#### Expected behaviour:
The `0` should say `2`.

#### Note:
Pressing `Tab` to move the cursor to the next occurrence, updates to the correct mode-line text `Iedit:3/3`

#### System Info:
iedit-20180207.1019
Emacs 26.1
Windows 10 Version 1803

**Comment by victorhge** [comment]
Thanks for reporting.  It is just fixed in commit  63969e4
