### ISSUE TITLE
Conflict with diff-hl mode

### ISSUE THREAD

**Issue by lionel-** [victorhge/iedit#90]
There seems to be a conflict between iedit and diff-hl. Lines with diff-hl highlightings are not changed properly.

Discussed in https://github.com/victorhge/iedit/issues/84#issuecomment-394343938
Also reported at https://github.com/syl20bnr/spacemacs/issues/8527

Workaround in the wiki: https://github.com/victorhge/iedit/wiki#conflict-with-diff-hl-mode

```lisp
(add-hook 'iedit-mode-hook (lambda () (diff-hl-mode -1)))
(add-hook 'iedit-mode-end-hook (lambda () (diff-hl-mode +1)))
```

**Comment by victorhge** [comment]
It was an Emacs propblem and will be fixed in Emacs 26.2.
Refer to https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30823

We have the workaround anyway, so I think it should not be fixed in Iedit.
