### ISSUE TITLE
[Feature] iedit-hide-matched-lines feature.

### ISSUE THREAD

**Issue by zw963** [victorhge/iedit#93]
Emacs have a [HideLines](https://www.emacswiki.org/emacs/HideLines) package, do basically same things. 
iedit is so so awesome and powerful,  i think it should be no too hard to add this feature into, to complete remove the need to use hide lines. 

Thank very much.

**Comment by victorhge** [comment]
Just add this feature in
https://github.com/victorhge/iedit/commit/0c88144355d7a8b3dadb379ba2fb88ab4ce37880 .

**Comment by zw963** [comment]
Great! thank you very much!
