### ISSUE TITLE
How to prevent iedit from aborting after yank?

### ISSUE THREAD

**Issue by QiangF** [victorhge/iedit#95]
1. create an empty buffer
2. type the following two lines:

    abc
    abc

3. put the point inside abc, run iedit-mode
4. now if you yank before the a in the first abc, iedit doesn't abort,
   but if you yank before the a in the second abc, iedit abort

**Comment by QiangF** [comment]
iedit-lib.el


        (if (or (< beg (overlay-start occurrence))
                (> end (overlay-end occurrence)))
            (progn (setq iedit-aborting t) ; abort iedit-mode
                   (add-hook 'post-command-hook 'iedit-reset-aborting nil t))

Looks like modification-hooks is run after insert-in-front-hooks

**Comment by QiangF** [comment]
Seems the issue can be solved with

        (overlay-put occurrence 'modification-hooks '(iedit-update-occurrences-3))

    (defun iedit-update-occurrences-3 (occurrence after beg end &optional change)
    "Update all occurrences.
    This modification hook is triggered when a user edits any
    occurrence and is responsible for updating all other
    occurrences. Refer to `modification-hooks' for more details.
    Current supported edits are insertion, yank, deletion and
    replacement.  If this modification is going out of the
    occurrence, it will abort Iedit mode."
    (if undo-in-progress
        ;; If the "undo" change make occurrences different, it is going to mess up
        ;; occurrences.  So a check will be done after undo command is executed.
        (when (not iedit-post-undo-hook-installed)
            (add-hook 'post-command-hook 'iedit-post-undo nil t)
            (setq iedit-post-undo-hook-installed t))
        (when (not iedit-aborting)
        (message "*** modification hook ***")
        (message "beg %s" beg)
        (message "end %s" end)
        (message "after change is %s" after)
        (message "(overlay-start occurrence) %s " (overlay-start occurrence))
        (message "(overlay-end occurrence) %s " (overlay-end occurrence))
        ;; before modification
        (if (null after)
            (if (or (< beg (overlay-start occurrence))
                    (> end (overlay-end occurrence)))
                (progn  ; abort iedit-mode
                    (add-hook 'post-command-hook 'iedit-reset-aborting nil t))
            (setq iedit-before-modification-string
                    (buffer-substring-no-properties beg end))
            ;; Check if this is called twice before modification. When inserting
            ;; into zero-width occurrence or between two conjoined occurrences,
            ;; both insert-in-front-hooks and insert-behind-hooks will be
            ;; called.  Two calls will make `iedit-skip-modification-once' true.
            (setq iedit-skip-modification-once (not iedit-skip-modification-once)))
        ;; after modification
        (when (not iedit-buffering)
            (if iedit-skip-modification-once
                ;; Skip the first hook
                (setq iedit-skip-modification-once nil)
            (setq iedit-skip-modification-once t)
            (when (or (eq 0 change) ;; insertion
                        (eq beg end)  ;; deletion
                        (not (string= iedit-before-modification-string
                                    (buffer-substring-no-properties beg end))))
                (iedit-update-occurrences-2  occurrence after beg end change))))))))

**Comment by victorhge** [comment]
Not reproducable.
