### ISSUE TITLE
Incompitable with `dabbrev-expand`

### ISSUE THREAD

**Issue by netjune** [victorhge/iedit#97]
When iedit-mode is active, I press `Alt-/`(which run the command `dabbrev-expand`) to complete a word. After the completion, cursor goto unexpected position in the buffer.

It can be reproduced with `emacs -Q`.

emacs: 26.2
OS: macOS

**Comment by victorhge** [comment]
The root cause is that `replace-match'  records a point before change and goes back to the point after change.  But iedit modifies the buffer in modification hooks, which invalidates the recorded point.

Now since iedit updates occurrences in 'post-command-hooks', this should not be a problem.
