### ISSUE TITLE
suppress remap warning

### ISSUE THREAD

**Issue by andreyorst** [victorhge/iedit#98]
I want to map my own `iedit` function:

```emacs-lisp
(defun my/iedit-select-current-or-add ()
    "Select only current occurrence with `iedit-mode'.  Expand to
next occurrence if `iedit-mode' is already active."
    (interactive)
    (if (bound-and-true-p iedit-mode)
        (iedit-expand-down-to-occurrence)
      (iedit-mode 1)))
```

which imitates Sublime style marking to <kbd>Ctrl</kbd>+<kbd>;</kbd>, which is working, but annoying warning appears every first time I use this function, saying that:

```
Warning (iedit): Iedit default key "C-;" is occupied by my/iedit-select-current-or-add.
```

Which I already know about since it's me who changed that. How I can suppress this?

**Comment by victorhge** [comment]
There is an option `iedit-toggle-key-default' which is "C-;" by default.  Replacing it with something else should suppress the warning.

**Comment by andreyorst** [comment]
A bit awkward way, but it seems it works. Thanks
